# Generated by Django 5.1.7 on 2025-03-15 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gesture",
            unique_together={("user", "gesture")},
        ),
        migrations.AddField(
            model_name="gesture",
            name="_id",
            field=models.CharField(
                default="67d5a121243f9c2a2a52ab73",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveField(
            model_name="gesture",
            name="id",
        ),
    ]
