# Generated by Django 5.1.7 on 2025-03-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audios", "0002_alter_gesture_unique_together_gesture__id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gesture",
            name="audio_name",
        ),
        migrations.AlterField(
            model_name="gesture",
            name="_id",
            field=models.CharField(
                default="67d5cd004989ba42e7d4524d",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "_id",
                    models.CharField(
                        default="67d5cd004989ba42e7d4524c",
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("file", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="gesture",
            name="audio",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="audios.audio",
            ),
            preserve_default=False,
        ),
    ]
