# Generated by Django 5.1.7 on 2025-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audios", "0003_remove_gesture_audio_name_alter_gesture__id_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="_id",
            field=models.CharField(
                default="67d5d182313c3b9ab67667a8",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gesture",
            name="_id",
            field=models.CharField(
                default="67d5d182313c3b9ab67667a9",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
