# Generated by Django 5.1.7 on 2025-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audios", "0004_alter_audio__id_alter_gesture__id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="audio",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="audio",
            name="_id",
            field=models.CharField(
                default="67d601450706df0d2e796575",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gesture",
            name="_id",
            field=models.CharField(
                default="67d601450706df0d2e796576",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
