# Generated by Django 5.1.7 on 2025-03-15 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audios", "0005_alter_audio_unique_together_alter_audio__id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gesture",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="audio",
            name="_id",
            field=models.CharField(
                default="67d601b4b4f637b759a5eb19",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gesture",
            name="_id",
            field=models.CharField(
                default="67d601b4b4f637b759a5eb1a",
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="audio",
            unique_together={("user", "name")},
        ),
    ]
